apiVersion: apps/v1
kind: Deployment
metadata:
  name: axion-telemetry-query-service
  
  labels:
    app: axion-telemetry-query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: axion-telemetry-query-service
  template:
    metadata:
      labels:
        app: axion-telemetry-query-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: telemetry-query-service
          image: ghcr.io/asign796/axion-telemetry-query-service:57902cd
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: PORT
              value: "8080"
            - name: ENVIRONMENT
              value: "production"
          